### ISSUE TITLE
Build with system toml11

### ISSUE THREAD

**Issue by tim77** [Firstbober/wapanel#24]
Hello. Trying to package `wapanel` for official repos and there is some requirements related to bundled stuff. Is it possible to build `wapanel` with system `toml11`?

**Comment by Firstbober** [comment]
I will need to make some changes in `meson.build`. Today I will make necessary changes.

**Comment by Firstbober** [comment]
Here you go, now by using `-Dsystem_toml11` while building, project should use system headers. As toml11 does not come with any pkg-config file I cannot make it detect, If you don't have it then you get not the fanciest message from the compiler.

**Comment by tim77** [comment]
@Firstbober great, thanks. LGTM so far and submitted RR for Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1952716
