### ISSUE TITLE
Development is still ongoing or dead ?

### ISSUE THREAD

**Issue by sajcho** [Firstbober/wapanel#39]
Does it make sense to use this software?

**Comment by Firstbober** [comment]
Short answer: no.
Long answer: I really wanted to create a good taskbar/panel for Wayland compositors, so I can get XFCE experience on Wayfire. Wrote some code, removed some bugs and the result is a not so great product with many flaws originating from bad code design decisions and lack of experience. Maybe I will someday return and create something similar, but for now I would not recommend using this.

**Comment by sajcho** [comment]
Thanks.
